disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - force_unwrapping

excluded:
  - .build
  - .swiftpm
  - Tests/LinuxMain.swift

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
    error: 80

type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 80

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20
